"""rename department

Revision ID: 63abd14597e1
Revises: 7c6da6209591
Create Date: 2025-06-16 22:07:50.017906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63abd14597e1'
down_revision = '7c6da6209591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
